//SESSION
export const SET_SESSION = 'GET_SESSION'

//POINT
export const SET_POINT = 'SET_POINT'

//MESSAGES
export const REMOVE_MESSAGES = 'REMOVE_MESSAGES'
export const PUSH_MESSAGE = 'PUSH_MESSAGE'