import Head from 'next/head'
import Footer from './footer'
import ToastMsg from './toast'

export default function Layout({children}) {
    return (
        <>
            <div className='container p-4'>
                <header>
                    <Head>
                        <title>Pointing Game!</title>
                        <meta name="description" content="Generated by create next app" />
                        <link rel="icon" href="/favicon.ico" />
                    </Head>
                </header>
                <main>
                    <ToastMsg />
                    <div>
                        {children}
                    </div>
                </main>
                <footer className='bottom'>
                    <Footer/>
                </footer>
            </div>
        </>
    )
}