import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import {useState, useEffect, useRef} from 'react'
import { useRouter } from 'next/router'
import { getSession, postRequest, putRequest } from '../lib/request'

export default function Home() {

  const [team, setTeam] = useState('')
  const [pName, setName] = useState('')
  const [create, isCreate] = useState(true)

  const router = useRouter()
  const btnRef = useRef()
  
  useEffect(() => {
    const urlParams = new URLSearchParams(window.location.search);
    const sessionid = urlParams.get('sessionid');
    if(sessionid) {
      isCreate(false)
      getSession(sessionid).then(res => {
        sessionStorage.setItem('team', res.team)
        setTeam(res.team) 
      })
    }
  },[])

  useEffect(() => {
    const enabled = (team && team.trim().length > 0) 
    && (pName && pName.trim().length > 0)
    if(enabled) {
      btnRef.current.disabled=false
    } else {
      btnRef.current.disabled=true
    }
  }, [team, pName])

  const newSession = () => {
    sessionStorage.setItem('team', team)
    sessionStorage.setItem('name', pName)
    postRequest(team, pName).then(res => {
      sessionStorage.setItem('id',res._id)
      router.push(`/table?sessionid=${res._id}`)
    })
    
  }
  const joinSession = () => {
    const id = sessionStorage.getItem('id')
    putRequest(id, team, pName).then(res => {
      sessionStorage.setItem('name', pName)
      router.push(`/table?sessionid=${id}`)
    }).catch(e => console.error(e))
    
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Planning Poker!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet'></link> */}
      </Head>

      <main className={styles.main}>
        <div>
            <div className={styles.inputbox}>
              <label value="Team" name="Team">Team</label>
              <input type="text" 
                    label="Name" 
                    id="session-name-txt" 
                    onChange={(e) => setTeam(e.target.value)}
                    value={team}
                    disabled={!create}/>
              <label value="Name" name="Name">Name</label>
              <input type="text" 
                    label="Name" 
                    id="session-name-txt" 
                    onChange={(e) => setName(e.target.value)}
                    value={pName}/>
              {create && 
                <button onClick={newSession} ref={btnRef}>Create</button>
              }
              {!create &&
                <button onClick={joinSession} ref={btnRef}>Join</button>
              }
              
            </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
