import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import {useState, useEffect, useRef} from 'react'
import { useRouter } from 'next/router'

export default function Home() {

  const [team, setTeam] = useState('')
  const [pName, setName] = useState('')
  const [create, isCreate] = useState(true)

  const router = useRouter()
  const btnRef = useRef()
  
  let sessionid

  useEffect(() => {
    const urlParams = new URLSearchParams(window.location.search);
    sessionid = urlParams.get('sessionid');
    if(sessionid) {
      isCreate(false)
      setTeam(sessionStorage.getItem('team')) // instead of session storage get from the db based on sessionid
    }
  },[])

  useEffect(() => {
    if(isEnabled()) {
      btnRef.current.disabled=false
    } else {
      btnRef.current.disabled=true
    }
  }, [team, pName])

  const isEnabled = () => {
    return (team && team.trim().length > 0) 
            && (pName && pName.trim().length > 0)
  }

  const newSession = () => {
    if(team.length === 0){
      alert(`Please enter team name`)
    } else if(pName.length === 0) {
      alert(`Please enter your name`)
    } else {
      sessionid = Date.now()
      sessionStorage.setItem('id', sessionid)
      sessionStorage.setItem('team', team)
      sessionStorage.setItem('name', pName)
      router.push(`/table?sessionid=${sessionid}`)
    }
  }

  const joinSession = () => {
    if(team.length === 0){
      alert(`Please enter team name`)
    } else if(pName.length === 0) {
      alert(`Please enter your name`)
    } else {
      sessionStorage.setItem('team', team)
      sessionStorage.setItem('name', pName)
      router.push(`/table?sessionid=${sessionStorage.getItem('id')}`)
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Planning Poker!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet'></link>
      </Head>

      <main className={styles.main}>
        <div>
            <div className={styles.inputbox}>
              <label value="Team" name="Team">Team</label>
              <input type="text" 
                    label="Name" 
                    id="session-name-txt" 
                    onChange={(e) => setTeam(e.target.value)}
                    value={team}
                    disabled={!create}/>
              <label value="Name" name="Name">Name</label>
              <input type="text" 
                    label="Name" 
                    id="session-name-txt" 
                    onChange={(e) => setName(e.target.value)}
                    value={pName}/>
              {create && 
                <button onClick={newSession} ref={btnRef}>Create</button>
              }
              {!create &&
                <button onClick={joinSession} ref={btnRef}>Join</button>
              }
              
            </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
